FROM centos:8
CMD [ "/usr/sbin/init" ]
RUN curl --silent --location https://rpm.nodesource.com/setup_14.x | bash -
RUN yum install nodejs -y
RUN curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
RUN rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg
RUN yum install yarn -y
# RUN yum -y install nginx

# ssl
# RUN dnf install epel-release -y
# RUN dnf upgrade -y
# RUN dnf install snapd -y
# RUN systemctl enable --now snapd.socket
# RUN ln -s /var/lib/snapd/snap /snap
# RUN setenforce 0
# RUN snap install core;snap refresh core
# RUN snap install --classic certbot

# RUN certbot --nginx
# RUN certbot -d kumkum.ga

