version: "3.7"
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=a0935745150@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
    networks:
      - shopee-network
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  react_build:
    build:
      context: .
      dockerfile: dockerfile
    container_name: react_compiler
    volumes:
      - ${opt_path}/:/opt/shopee-ui
    working_dir: "/opt/shopee-ui"
    networks:
      shopee-network:
        ipv4_address: 172.21.0.12
    logging:
      driver: "json-file"
      options:
        max-size: "10240k"
        max-file: "10"
    command:
      - /bin/bash
      - -c
      - |
        npm install
        rm -rf ./${compiler_folder}
        sleep 1
        yarn build
        yarn start -p 3111
        tail -f /dev/null
    stdin_open: true
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react_build.rule=Host(`kumkum.ga`)"
      - "traefik.http.services.react_build.loadbalancer.server.port=3111"
      - "traefik.http.routers.react_build.entrypoints=websecure"
      - "traefik.http.routers.react_build.tls.certresolver=myresolver"

networks:
  shopee-network:
    external: true
    name: shopee-network
