version: "3.7"
services:
  react_build:
    build:
      context: .
      dockerfile: dockerfile
    container_name: react_compiler
    volumes:
      - ${opt_path}/:/opt/shopee-ui
    working_dir: "/opt/shopee-ui"
    ports:
      - 3111:3111
    networks:
      shopee-network:
        ipv4_address: 172.21.0.12
    logging:
      driver: "json-file"
      options:
        max-size: "10240k"
        max-file: "10"
    command:
      - /bin/bash
      - -c
      - |
        npm install
        rm -rf ${compiler_folder}
        sleep 1
        yarn build
        yarn start -p 3111
        tail -f /dev/null
    stdin_open: true
    tty: true

#   react_run_linux:
#       build:
#         context: .
#         dockerfile: dockerfile
#       depends_on:
#           react_build:
#             condition: service_completed_successfully
#       container_name: react_linux
#       volumes:
#         - ${opt_path}/docker_build_react/compiler:/opt/shopee-ui/compiler
#         - ${opt_path}/package.json:/opt/shopee-ui/package.json
#       restart: always
#       working_dir: "/opt/shopee-ui/compiler/.next"
#       ports:
#         - 3111:3111
#       networks:
#         shopee-network:
#           ipv4_address: 172.21.0.12
#       logging:
#         driver: "json-file"
#         options:
#           max-size: "10240k"
#           max-file: "10"
#       command:
#         - /bin/bash
#         - -c
#         - |
#           yarn start -p 3111
#           tail -f /dev/null
#       stdin_open: true
#       tty: true

networks:
  shopee-network:
      external: true
      name: shopee-network