version: "3.7"
services:
  react_build:
    build:
      context: .
      dockerfile: dockerfile
    container_name: react_compiler
    volumes:
      - ${opt_path}/:/opt/shopee-ui
    working_dir: "/opt/shopee-ui"
    networks:
      shopee-network:
        ipv4_address: 172.21.0.12
    logging:
      driver: "json-file"
      options:
        max-size: "10240k"
        max-file: "10"
    command:
      - /bin/bash
      - -c
      - |
        npm install
        rm -rf ./${compiler_folder}
        sleep 1
        yarn build
        yarn start -p 80
        tail -f /dev/null
    stdin_open: true
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`kumkumtraefik.ml`)"
      # - "traefik.port=443"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

networks:
  shopee-network:
    external: true
    name: shopee-network
