version: "3.7"
services:
  react_build:
    build:
      context: .
      dockerfile: dockerfile
    container_name: react_compiler
    volumes:
      - ${opt_path}/:/opt/shopee-ui
    working_dir: "/opt/shopee-ui"
    ports:
      - 3111:3111
    networks:
      shopee-network:
        ipv4_address: 172.21.0.12
    logging:
      driver: "json-file"
      options:
        max-size: "10240k"
        max-file: "10"
    command:
      - /bin/bash
      - -c
      - |
        npm install
        rm -rf ./${compiler_folder}
        sleep 1
        yarn build
        yarn start -p 3111
        tail -f /dev/null
    stdin_open: true
    tty: true
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:kumkum.ga"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
      - "traefik.admin.frontend.rule=Host:kumkum.ga"
      - "traefik.admin.protocol=https"
      - "traefik.admin.port=443"

networks:
  shopee-network:
    external: true
    name: shopee-network
