debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    [entryPoints.http.proxyProtocol]
      insecure = true
      trustedIPs = ["172.21.0.12"]
  [entryPoints.https]
  address = ":443"
   [entryPoints.https.proxyProtocol]
      insecure = true
      trustedIPs = ["172.21.0.12"]
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "kumkum.ga"
watch = true
exposedByDefault = false

[acme]
email = "a0935745150@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"