debug = false

defaultEntryPoints = ["https", "http"]
logLevel = "ERROR"

[entryPoints]
	[entryPoints.http]
	address = ":80"
		[entryPoints.http.redirect]
		entryPoint = "https"
		[entryPoints.http.forwardedHeaders]
	[entryPoints.https]
		address = ":443"
		[entryPoints.https.forwardedHeaders]
		[entryPoints.https.tls]

[retry]

[docker]
domain = "kumkum.ga"
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false
watch = true

# [acme]
# email = "a0935745150@gmail.com"
# entryPoint = "https"
# onHostRule = true
# storage = "acme.json"
# [acme.httpChallenge]
# entryPoint = "http"

# [api]
# dashboard = true